# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 03:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='extra_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
