# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_client_extra_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='created_at',
            new_name='db_created_at',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='updated_at',
            new_name='db_updated_at',
        ),
        migrations.RenameField(
            model_name='periscopedashboard',
            old_name='created_at',
            new_name='db_created_at',
        ),
        migrations.RenameField(
            model_name='periscopedashboard',
            old_name='updated_at',
            new_name='db_updated_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='db_created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='db_updated_at',
        ),
    ]
