# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_auto_20170731_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='keep_in_sync',
            field=models.BooleanField(default=False),
        ),
    ]
