# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttentCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('email_address', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='America/Los_Angeles', max_length=50)),
            ],
            options={
                'db_table': 'attent_calendar',
            },
        ),
        migrations.CreateModel(
            name='AttentCalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.CharField(blank=True, db_index=True, default='', max_length=1024)),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_full_day', models.BooleanField(default=False)),
                ('creator_email_address', models.CharField(max_length=255)),
                ('organizer_email_address', models.CharField(max_length=255)),
                ('event_type', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'attent_calendar_event',
            },
        ),
        migrations.CreateModel(
            name='AttentCalendarEventHasExternalAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('response_status', models.CharField(default='', max_length=20)),
                ('attent_calendar_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attent_calendar.AttentCalendarEvent')),
            ],
            options={
                'db_table': 'attent_calendar_event_has_external_attendee',
            },
        ),
        migrations.CreateModel(
            name='AttentCalendarEventHasInternalAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('response_status', models.CharField(default='', max_length=20)),
                ('attent_calendar_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attent_calendar.AttentCalendarEvent')),
            ],
            options={
                'db_table': 'attent_calendar_event_has_internal_attendee',
            },
        ),
        migrations.CreateModel(
            name='ExternalAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('email_address', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'external_attendee',
            },
        ),
        migrations.CreateModel(
            name='InternalAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('email_address', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'internal_attendee',
            },
        ),
        migrations.AddField(
            model_name='attentcalendareventhasinternalattendee',
            name='internal_attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attent_calendar.InternalAttendee'),
        ),
        migrations.AddField(
            model_name='attentcalendareventhasexternalattendee',
            name='external_attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attent_calendar.ExternalAttendee'),
        ),
    ]
