# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visualizer', '0001_initial'),
        ('google_calendar', '0001_initial'),
        ('attent_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentcalendarevent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.visualizer.Client'),
        ),
        migrations.AddField(
            model_name='attentcalendarevent',
            name='external_attendees',
            field=models.ManyToManyField(related_name='attent_calendar_events', related_query_name='attent_calendar_event', through='apps.attent_calendar.AttentCalendarEventHasExternalAttendee', to='apps.attent_calendar.ExternalAttendee'),
        ),
        migrations.AddField(
            model_name='attentcalendarevent',
            name='google_calendar_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.google_calendar.GoogleCalendarEvent'),
        ),
        migrations.AddField(
            model_name='attentcalendarevent',
            name='internal_attendees',
            field=models.ManyToManyField(related_name='attent_calendar_events', related_query_name='attent_calendar_event', through='apps.attent_calendar.AttentCalendarEventHasInternalAttendee', to='apps.attent_calendar.InternalAttendee'),
        ),
        migrations.AddField(
            model_name='attentcalendar',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.visualizer.Client'),
        ),
        migrations.AddField(
            model_name='attentcalendar',
            name='google_calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.google_calendar.GoogleCalendar'),
        ),
    ]
