# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attent_calendar', '0003_auto_20170805_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentcalendar',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='attentcalendar',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='attentcalendar',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
    ]
