# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 00:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visualizer', '0003_auto_20170810_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceCustomFieldMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.CharField(db_index=True, max_length=50)),
                ('mapping', django.contrib.postgres.fields.hstore.HStoreField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visualizer.Client')),
            ],
            options={
                'db_table': 'salesforce_custom_field_mapping',
            },
        ),
    ]
