# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0002_auto_20170905_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforceaccount',
            name='number_of_employees',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
