# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0003_auto_20170905_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforceaccount',
            name='created_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='last_activity_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='last_modified_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='last_viewed_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='master_record_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='number_of_employees',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
