# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0004_auto_20170905_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforceaccount',
            name='created_by_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='created_date',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='last_activity_date',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='last_modified_by_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='last_modified_date',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='last_viewed_date',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='master_record_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='number_of_employees',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='owner_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='salesforceaccount',
            name='sfdc_id',
            field=models.TextField(db_index=True),
        ),
    ]
