# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0005_auto_20170905_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceaccount',
            name='is_deleted',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
