# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0007_auto_20170906_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesforceaccount',
            old_name='extra_data',
            new_name='rest_of_data',
        ),
    ]
