# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0010_auto_20170907_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesforceaccount',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='salesforceaccounthistory',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='salesforcecontact',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='salesforcecontacthistory',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='salesforceevent',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='salesforcelead',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='salesforceopportunity',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='salesforceopportunityfieldhistory',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='salesforceopportunityhistory',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='salesforcetask',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='salesforceuser',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='salesforceuserrole',
            name='is_deleted',
        ),
    ]
