# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0004_auto_20171010_1323'),
        ('salesforce', '0012_auto_20171023_1115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesforceaccount',
            unique_together=set([('client', 'sfdc_id')]),
        ),
    ]
