# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0004_auto_20171010_1323'),
        ('salesforce', '0013_auto_20171023_1123'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='salesforceaccount',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='salesforceaccounthistory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='salesforcecontact',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='salesforcecontacthistory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='salesforceevent',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='salesforcelead',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='salesforceopportunity',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='salesforceopportunityfieldhistory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='salesforceopportunityhistory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='salesforcetask',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='salesforceuser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='salesforceuserrole',
            managers=[
            ],
        ),
        migrations.AlterUniqueTogether(
            name='salesforceaccounthistory',
            unique_together=set([('client', 'sfdc_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesforcecontact',
            unique_together=set([('client', 'sfdc_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesforcecontacthistory',
            unique_together=set([('client', 'sfdc_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesforceevent',
            unique_together=set([('client', 'sfdc_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesforcelead',
            unique_together=set([('client', 'sfdc_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesforceopportunity',
            unique_together=set([('client', 'sfdc_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesforceopportunityfieldhistory',
            unique_together=set([('client', 'sfdc_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesforceopportunityhistory',
            unique_together=set([('client', 'sfdc_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesforcetask',
            unique_together=set([('client', 'sfdc_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesforceuser',
            unique_together=set([('client', 'sfdc_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesforceuserrole',
            unique_together=set([('client', 'sfdc_id')]),
        ),
    ]
