# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google_calendar', '0015_auto_20170801_0008'),
        ('visualizer', '0003_auto_20170731_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizer.Client')),
                ('google_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_calendar.GoogleCalendar')),
                ('timezone', models.CharField(default='America/Los_Angeles', max_length=50)),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attent_calendar',
            },
        ),
    ]
