# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0015_auto_20170801_0008'),
        ('visualizer', '0003_auto_20170731_2023'),
        ('attent_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentCalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.CharField(blank=True, default='', max_length=1024)),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('creator_email_address', models.CharField(max_length=255)),
                ('organizer_email_address', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizer.Client')),
            ],
            options={
                'db_table': 'attent_calendar_event',
            },
        ),
        migrations.CreateModel(
            name='AttentCalendarEventHasExternalAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('response_status', models.CharField(default='', max_length=20)),
                ('attent_calendar_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attent_calendar.AttentCalendarEvent')),
            ],
            options={
                'db_table': 'attent_calendar_event_has_external_attendee',
            },
        ),
        migrations.CreateModel(
            name='AttentCalendarEventHasInternalAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('response_status', models.CharField(default='', max_length=20)),
                ('attent_calendar_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attent_calendar.AttentCalendarEvent')),
            ],
            options={
                'db_table': 'attent_calendar_event_has_internal_attendee',
            },
        ),
        migrations.CreateModel(
            name='ExternalAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('email_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'external_attendee',
            },
        ),
        migrations.CreateModel(
            name='InternalAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('email_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'internal_attendee',
            },
        ),
        migrations.AddField(
            model_name='attentcalendareventhasinternalattendee',
            name='internal_attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attent_calendar.InternalAttendee'),
        ),
        migrations.AddField(
            model_name='attentcalendareventhasexternalattendee',
            name='external_attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attent_calendar.ExternalAttendee'),
        ),
        migrations.AddField(
            model_name='attentcalendarevent',
            name='external_attendees',
            field=models.ManyToManyField(through='attent_calendar.AttentCalendarEventHasExternalAttendee', to='attent_calendar.ExternalAttendee'),
        ),
        migrations.AddField(
            model_name='attentcalendarevent',
            name='google_calendar_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_calendar.GoogleCalendarEvent'),
        ),
        migrations.AddField(
            model_name='attentcalendarevent',
            name='internal_attendees',
            field=models.ManyToManyField(through='attent_calendar.AttentCalendarEventHasInternalAttendee', to='attent_calendar.InternalAttendee'),
        ),
    ]
