# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attent_calendar', '0002_auto_20170802_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalattendee',
            name='email_address',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='internalattendee',
            name='email_address',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
