# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attent_calendar', '0003_auto_20170802_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentcalendarevent',
            name='event_type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attentcalendarevent',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1024),
        ),
    ]
