# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attent_calendar', '0004_auto_20170802_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attentcalendarevent',
            name='event_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
