# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attent_calendar', '0006_auto_20170802_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attentcalendarevent',
            name='external_attendees',
            field=models.ManyToManyField(related_name='attent_calendar_events', related_query_name='attent_calendar_event', through='attent_calendar.AttentCalendarEventHasExternalAttendee', to='attent_calendar.ExternalAttendee'),
        ),
        migrations.AlterField(
            model_name='attentcalendarevent',
            name='internal_attendees',
            field=models.ManyToManyField(related_name='attent_calendar_events', related_query_name='attent_calendar_event', through='attent_calendar.AttentCalendarEventHasInternalAttendee', to='attent_calendar.InternalAttendee'),
        ),
    ]
