# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attent_calendar', '0007_auto_20170802_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentcalendarevent',
            name='is_full_day',
            field=models.BooleanField(default=False),
        ),
    ]
