# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 10:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visualizer', '0003_auto_20170810_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outreach_id', models.IntegerField(db_index=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.visualizer.Client')),
                ('name', models.CharField(max_length=100, default='', null=True)),
                ('natural_name', models.CharField(max_length=100, default='', null=True)),
                ('company_type', models.CharField(default='', max_length=20)),
                ('domain', models.CharField(max_length=255)),
                ('website_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outreach_account',
            },
        ),
        migrations.CreateModel(
            name='OutreachCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('user_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('outcome', models.CharField(default='', max_length=20)),
                ('answered_at', models.DateTimeField(default=None, null=True)),
                ('completed_at', models.DateTimeField(default=None, null=True)),
                ('direction', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outreach_call',
            },
        ),
        migrations.CreateModel(
            name='OutreachMailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.visualizer.Client')),
                ('mailing_type', models.CharField(default='', max_length=30)),
                ('mailbox_address', models.CharField(db_index=True, default='', max_length=255)),
                ('subject', models.CharField(default='', max_length=255)),
                ('body_text', models.TextField(default='')),
                ('open_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('opened_at', models.DateTimeField(default=None, null=True)),
                ('replied_at', models.DateTimeField(default=None, null=True)),
                ('bounced_at', models.DateTimeField(default=None, null=True)),
                ('marked_as_spam_at', models.DateTimeField(default=None, null=True)),
                ('scheduled_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outreach_mailing',
            },
        ),
        migrations.CreateModel(
            name='OutreachProspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outreach_id', models.IntegerField(db_index=True)),
                ('outreach_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outreach.OutreachAccount')),
                ('engaged_score', models.IntegerField()),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('middle_name', models.CharField(default='', max_length=20)),
                ('occupation', models.CharField(default='', max_length=40)),
                ('title', models.CharField(default='', max_length=40)),
                ('open_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('engaged_at', models.DateTimeField()),
                ('opted_out_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outreach_prospect',
            },
        ),
        migrations.CreateModel(
            name='OutreachUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outreach_id', models.IntegerField(db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.visualizer.Client')),
                ('email_address', models.CharField(db_index=True, max_length=255)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outreach_user',
            },
        ),
        migrations.AddField(
            model_name='outreachmailing',
            name='outreach_prospect',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='outreach.OutreachProspect'),
        ),
    ]
