# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_auto_20170814_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreachprospect',
            name='outreach_account',
        ),
        migrations.AddField(
            model_name='outreachprospect',
            name='outreach_account_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
