# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_auto_20170810_0616'),
        ('outreach', '0003_auto_20170814_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachprospect',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visualizer.Client'),
        ),
    ]
