# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0004_outreachprospect_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachprospect',
            name='outreach_owner_user_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
