# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0005_outreachprospect_outreach_owner_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachprospect',
            name='outreach_account_id',
            field=models.IntegerField(blank=True, db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='outreachprospect',
            name='outreach_owner_user_id',
            field=models.IntegerField(blank=True, db_index=True, default=None),
        ),
    ]
