# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0007_auto_20170815_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachprospect',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='outreachprospect',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
