# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0011_outreachcall_outreach_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreachcall',
            name='prospect_data',
        ),
        migrations.RemoveField(
            model_name='outreachcall',
            name='user_data',
        ),
        migrations.AddField(
            model_name='outreachcall',
            name='outreach_prospect_id',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='outreachcall',
            name='outreach_user_id',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='outreachmailing',
            name='click_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='outreachmailing',
            name='open_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
