# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0012_auto_20170816_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachmailing',
            name='body_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='outreachmailing',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
