# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0014_auto_20170816_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachcall',
            name='outcome',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
