# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0015_auto_20170816_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachcall',
            name='record_url',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
