# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0017_auto_20170816_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachprospect',
            name='all_email_addresses',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='outreachprospect',
            name='primary_email_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
