# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_auto_20170810_0616'),
        ('outreach', '0018_auto_20170819_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachProspectV1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('outreach_id', models.IntegerField(db_index=True)),
                ('email_address', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number_personal', models.CharField(blank=True, default='', max_length=20)),
                ('phone_number_work', models.CharField(blank=True, default='', max_length=20)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.visualizer.Client')),
            ],
            options={
                'db_table': 'outreach_prospect_v1',
            },
        ),
        migrations.RemoveField(
            model_name='outreachprospect',
            name='primary_email_address',
        ),
    ]
