# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0004_auto_20171010_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='warehouse_sql_view',
            field=models.TextField(default=None, null=True),
        ),
    ]
