# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0007_client_slack_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='warehouse_view_name',
            new_name='warehouse_view_name_oppty',
        ),
        migrations.RemoveField(
            model_name='client',
            name='warehouse_view_definition',
        ),
        migrations.AddField(
            model_name='client',
            name='warehouse_view_name_contact',
            field=models.TextField(default=None, null=True),
        ),
    ]
