# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0008_auto_20171120_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='warehouse_view_name_account',
            field=models.TextField(default=None, null=True),
        ),
    ]
