# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0003_auto_20170805_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendar',
            name='sync_user_access_role',
            field=models.CharField(default='freeBusyReader', max_length=30),
        ),
    ]
