# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.CharField(max_length=255)),
                ('sync_detail', django.contrib.postgres.fields.jsonb.JSONField(default={'sync_state': 'uninitialized'})),
                ('sync_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sync_user_history', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'google_calendar',
            },
        ),
    ]
