# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 02:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('google_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarListSync',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sync_detail', django.contrib.postgres.fields.jsonb.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'google_calendar_list_sync',
            },
        ),
        migrations.AddField(
            model_name='googlecalendar',
            name='last_sync_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
