# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0002_auto_20170726_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarApiLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email_address', models.CharField(max_length=127)),
                ('resource', models.CharField(max_length=50)),
                ('args', django.contrib.postgres.fields.jsonb.JSONField()),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'google_calendar_api_log',
            },
        ),
    ]
