# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0002_auto_20170805_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendar',
            name='is_kept_in_sync',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1024),
        ),
    ]
