# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0003_googlecalendarapilogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecalendarlistsync',
            name='updated_at',
        ),
    ]
