# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0004_remove_googlecalendarlistsync_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendar',
            name='etag',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='googlecalendar',
            name='is_kept_in_sync',
            field=models.BooleanField(default=True),
        ),
    ]
