# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0005_auto_20170728_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendar',
            name='last_sync_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
