# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import google_calendar.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('google_calendar', '0006_auto_20170728_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'google_calendar_event',
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarListSyncState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_calendar_list_sync_state',
            },
            bases=(models.Model, google_calendar.mixins.SyncParamsMixin),
        ),
        migrations.RemoveField(
            model_name='googlecalendarlistsync',
            name='user',
        ),
        migrations.AlterField(
            model_name='googlecalendarapilogs',
            name='user_email_address',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='GoogleCalendarListSync',
        ),
    ]
