# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0009_remove_googlecalendar_etag'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendar',
            name='timezone',
            field=models.CharField(default='America/Los_Angeles', max_length=50),
        ),
    ]
