# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0011_auto_20170731_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendarevent',
            name='process_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='event_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='htmlLink',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='recurring_event_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
