# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0012_auto_20170731_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googlecalendarevent',
            old_name='htmlLink',
            new_name='html_link',
        ),
        migrations.RemoveField(
            model_name='googlecalendarapilogs',
            name='created_at',
        ),
    ]
