# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0013_auto_20170731_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecalendarevent',
            name='end',
        ),
        migrations.RemoveField(
            model_name='googlecalendarevent',
            name='start',
        ),
    ]
