# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 00:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0014_auto_20170801_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendarevent',
            name='end',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='googlecalendarevent',
            name='start',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
