# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0015_auto_20170801_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='process_time',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
