# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 02:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0016_auto_20170802_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='attendees',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
