# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 02:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_connection', '0003_apisyncstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisyncstatus',
            name='start',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 8, 21, 2, 59, 41, 786572, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
